Feat: Refine Footer Component
Open-SGF/opensgf.org pull request #92
Opened 2022-09-17 00:51 UTC by ethanzitting

2022-09-17 16:06 UTC, fredlawl requested changes
I think I saw some linter issues that need to be worked out, otherwise looks pretty good. I left a few comments about adjusting our social urls.

2022-09-18 14:29 UTC, ethanzitting commented on src/components/Footer/Footer.tsx
> +            url: 'https://discord.com/',
Good catch, implemented!

2022-09-18 14:29 UTC, ethanzitting commented on src/components/Footer/Footer.tsx
> +            url: 'https://www.meetup.com/',
Good catch, implemented!

2022-09-18 14:29 UTC, ethanzitting commented on src/components/Footer/Footer.tsx
> +        },
Sounds good.

2022-09-18 14:29 UTC, ethanzitting commented on src/components/Footer/Footer.tsx
> +        }
Sounds Good.

2022-09-18 17:39 UTC, fredlawl approved these changes

2022-09-20 16:15 UTC, merged